# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1be7ba737eff44c2c9f95a5982e0b9b845cc07d1a20479db6ac05898b93b9bd8c0ac43ac5946fb67c80226cf17d70644642de8e7c898b228309bf331e2495964

test:
  secret_key_base: 3aecf6be5c045d90fbba545fffceaa3e256c7ec49935a23ee7319b71263a29e387a2bdb6f21776017aed2fb8693c10c74331d00f305fe0522da8f7fb2076249f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
